'use client';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import type {Candidate,State} from '@/lib/ats';
import {type Template,type Assessment,type Collective,type Scores,defaultTemplate,blankScores,blankEvidence,pillars,score,band,critical,templateTasks,localDate} from '@/lib/process';
const when=(s:string)=>new Date(s).toLocaleString('pt-BR');
function ScoreBadge({scores}:{scores:Scores}){return <div className="score-summary"><strong>{score(scores)===null?'Não concluída':`${score(scores)} / 100`}</strong><span>{band(scores)}</span>{critical(scores)&&<p className="warning">Alerta crítico: Mentalidade ou Ação com nota 1 ou 2. Discutir as evidências antes da decisão.</p>}</div>;}
function ScoreFields({value,onChange}:{value:{scores:Scores;evidence:ReturnType<typeof blankEvidence>};onChange:(value:{scores:Scores;evidence:ReturnType<typeof blankEvidence>})=>void}){return <><p className="footnote">1 Incompatível · 2 Abaixo do esperado · 3 Adequado · 4 Forte · 5 Excepcional. Sem nota significa não avaliado.</p>{pillars.map(p=><div className="pillar-row" key={p.key}><label>{p.name} · {p.weight}%<select value={value.scores[p.key]??''} onChange={e=>onChange({...value,scores:{...value.scores,[p.key]:e.target.value?Number(e.target.value):null}})}><option value="">Não avaliado</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Evidências de {p.name.toLowerCase()}<Textarea value={value.evidence[p.key]} onChange={e=>onChange({...value,evidence:{...value.evidence,[p.key]:e.target.value}})} placeholder="Contexto, ação concreta, resultado e aprendizado"/></label></div>)}<ScoreBadge scores={value.scores}/></>;}

export function CandidateProcess({candidate:c,state,onChange,userName,onEditing}:{candidate:Candidate;state:State;onChange:(c:Candidate)=>void;userName:string;onEditing:(editing:boolean)=>void}){
 const [individual,setIndividual]=useState<Assessment|null>(null),[collective,setCollective]=useState<Collective|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{onEditing(!!individual||!!collective);return()=>onEditing(false);},[individual,collective,onEditing]);
 const template=state.templates.find(t=>t.id===c.templateId);
 const stamp=(text:string)=>[{at:new Date().toISOString(),text},...c.history];
 function startIndividual(){setMessage('');setIndividual({id:crypto.randomUUID(),interviewer:userName,stage:c.stage,at:new Date().toISOString(),scores:blankScores(),evidence:blankEvidence(),positives:'',risks:'',potential:'Não avaliado',recommendation:'Pendente',summary:''});}
 function storeIndividual(){if(!individual)return;if(!individual.interviewer.trim()||pillars.some(p=>individual.scores[p.key]!==null&&!individual.evidence[p.key].trim())){setMessage('Informe o entrevistador e uma evidência para cada pilar pontuado.');return;}onChange({...c,assessments:[...(c.assessments||[]),{...individual,at:new Date().toISOString()}],history:stamp('Avaliação MHMA individual registrada: '+individual.interviewer)});setIndividual(null);setMessage('Avaliação incluída. Salve a ficha do candidato para gravar.');}
 function startCollective(){setMessage('');setCollective(c.collective?structuredClone(c.collective):{participants:[...new Set((c.assessments||[]).map(a=>a.interviewer))],at:new Date().toISOString(),scores:blankScores(),evidence:blankEvidence(),decision:'Reserva',rationale:'',criticalJustification:'',recordedBy:userName});}
 function storeCollective(){if(!collective)return;const p=collective.participants.map(s=>s.trim()).filter(Boolean);if(!p.length||!collective.recordedBy.trim()||score(collective.scores)===null||Object.values(collective.evidence).some(e=>!e.trim())||!collective.rationale.trim()||(critical(collective.scores)&&!collective.criticalJustification.trim())){setMessage('Informe participantes, quatro notas com evidências, decisão, justificativa e discussão dos alertas.');return;}onChange({...c,collective:{...collective,participants:p,at:new Date().toISOString()},collectiveHistory:c.collective?[...(c.collectiveHistory||[]),c.collective]:(c.collectiveHistory||[]),history:stamp('Discussão coletiva MHMA registrada: '+p.join(', '))});setCollective(null);setMessage('Discussão incluída. Salve a ficha do candidato para gravar.');}
 return <section className="process-panel"><h2>Roteiro e avaliação MHMA</h2><p className="footnote">As alterações desta seção são gravadas ao salvar o candidato.</p><Tabs defaultValue="tasks"><TabsList className="process-tabs"><TabsTrigger value="tasks">Roteiro</TabsTrigger><TabsTrigger value="mhma">MHMA</TabsTrigger><TabsTrigger value="practice">Teste prático</TabsTrigger></TabsList>
 <TabsContent value="tasks"><label>Modelo da função<select value={c.templateId||''} onChange={e=>onChange({...c,templateId:e.target.value})}><option value="">Sem modelo</option>{state.templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><Button type="button" variant="outline" disabled={!template} onClick={()=>{const tasks=templateTasks(template,c.stage,c.owner,state.holidays).filter(t=>!(c.tasks||[]).some(old=>old.templateTaskId===t.templateTaskId&&old.stage===c.stage));onChange({...c,tasks:[...(c.tasks||[]),...tasks],history:stamp(`Roteiro aplicado à etapa ${c.stage}: ${tasks.length} tarefa(s)`)});}}>Aplicar tarefas à etapa atual</Button><p className="footnote">D1 é o primeiro dia útil da etapa. Sábados, domingos e feriados cadastrados não contam. Prazos já criados são preservados.</p>{template&&<details><summary>Perfil, perguntas e próximos passos</summary><p className="preline">{template.requirements}</p><p className="preline">{template.questions}</p><ol className="template-preview">{template.tasks.map(t=><li key={t.id}><strong>{t.stage} · D{t.day}</strong> {t.title} {t.required?'(obrigatória)':''}</li>)}</ol></details>}
 {(c.tasks||[]).map(task=><div className="task-item" key={task.id}><label className="task-check"><input type="checkbox" checked={task.done} onChange={e=>onChange({...c,tasks:c.tasks!.map(t=>t.id===task.id?{...t,done:e.target.checked,completedAt:e.target.checked?new Date().toISOString():''}:t),history:stamp(`${e.target.checked?'Concluída':'Reaberta'}: ${task.title}`)})}/><span><strong>{task.title}</strong><small>{task.stage} · {task.required?'Obrigatória':'Opcional'}{!task.done&&task.due&&task.due<localDate()?' · Atrasada':''}</small></span></label><div className="form-grid"><label>Responsável<Input value={task.owner} onChange={e=>onChange({...c,tasks:c.tasks!.map(t=>t.id===task.id?{...t,owner:e.target.value}:t)})}/></label><label>Prazo<Input type="date" value={task.due} onChange={e=>onChange({...c,tasks:c.tasks!.map(t=>t.id===task.id?{...t,due:e.target.value}:t)})}/></label></div></div>)}{!c.tasks?.length&&<p className="footnote">Nenhuma tarefa cadastrada.</p>}</TabsContent>
 <TabsContent value="mhma"><div className="actions"><Button type="button" variant="outline" onClick={startIndividual}>Nova avaliação individual</Button><Button type="button" onClick={startCollective}>Registrar discussão final</Button></div><p className="footnote">Cada entrevistador mantém seu registro. A nota final é definida na discussão conjunta; não é uma média automática.</p>{message&&<p role="status" className="warning">{message}</p>}{(c.assessments||[]).map(a=><details key={a.id} className="assessment"><summary>{a.interviewer} · {a.stage} · {score(a.scores)===null?'Incompleta':score(a.scores)+' pontos'}</summary><p>{when(a.at)}</p><ScoreBadge scores={a.scores}/>{pillars.map(p=><p key={p.key}><strong>{p.name}: {a.scores[p.key]??'Não avaliado'}</strong><br/>{a.evidence[p.key]}</p>)}<p>Positivos: {a.positives||'Não informado'}</p><p>Alertas: {a.risks||'Não informado'}</p><p>Potencial: {a.potential} · Recomendação: {a.recommendation}</p><p>{a.summary}</p><Button type="button" variant="outline" onClick={()=>{setIndividual({...structuredClone(a),id:crypto.randomUUID(),at:new Date().toISOString()});setMessage('Uma nova versão será registrada; a anterior permanece no histórico.');}}>Complementar em novo registro</Button></details>)}
 {c.collective&&<div className="collective-summary"><h3>Decisão conjunta: {c.collective.decision}</h3><p>{c.collective.participants.join(', ')} · {when(c.collective.at)}</p><ScoreBadge scores={c.collective.scores}/><p className="preline">{c.collective.rationale}</p>{pillars.map(p=><p key={p.key}><strong>{p.name}:</strong> {c.collective!.evidence[p.key]}</p>)}{c.collective.criticalJustification&&<p>Discussão dos alertas: {c.collective.criticalJustification}</p>}</div>}{!!c.collectiveHistory?.length&&<details><summary>Discussões finais anteriores ({c.collectiveHistory.length})</summary>{c.collectiveHistory.map((f,i)=><p key={i}>{when(f.at)} · {f.participants.join(', ')} · {f.decision} · {score(f.scores)} pontos<br/>{f.rationale}</p>)}</details>}
 {individual&&<div className="evaluation-editor"><h3>Avaliação individual</h3><div className="form-grid"><label>Entrevistador *<Input value={individual.interviewer} onChange={e=>setIndividual({...individual,interviewer:e.target.value})}/></label><label>Etapa<select value={individual.stage} onChange={e=>setIndividual({...individual,stage:e.target.value})}>{state.stages.map(s=><option key={s}>{s}</option>)}</select></label></div><ScoreFields value={individual} onChange={v=>setIndividual({...individual,...v})}/><label>Evidências positivas<Textarea value={individual.positives} onChange={e=>setIndividual({...individual,positives:e.target.value})}/></label><label>Alertas e riscos<Textarea value={individual.risks} onChange={e=>setIndividual({...individual,risks:e.target.value})}/></label><div className="form-grid"><label>Potencial<select value={individual.potential} onChange={e=>setIndividual({...individual,potential:e.target.value as Assessment['potential']})}>{['Não avaliado','Baixo','Médio','Alto'].map(s=><option key={s}>{s}</option>)}</select></label><label>Recomendação<select value={individual.recommendation} onChange={e=>setIndividual({...individual,recommendation:e.target.value as Assessment['recommendation']})}>{['Pendente','Avançar','Reserva','Não avançar'].map(s=><option key={s}>{s}</option>)}</select></label></div><label>Síntese<Textarea value={individual.summary} onChange={e=>setIndividual({...individual,summary:e.target.value})}/></label><Button type="button" onClick={storeIndividual}>Incluir avaliação na ficha</Button> <Button type="button" variant="ghost" onClick={()=>setIndividual(null)}>Cancelar avaliação</Button></div>}
 {collective&&<div className="evaluation-editor"><h3>Discussão coletiva final</h3><label>Participantes — um por linha *<Textarea value={collective.participants.join('\n')} onChange={e=>setCollective({...collective,participants:e.target.value.split('\n')})}/></label><label>Registrado por *<Input value={collective.recordedBy} onChange={e=>setCollective({...collective,recordedBy:e.target.value})}/></label><ScoreFields value={collective} onChange={v=>setCollective({...collective,...v})}/><label>Decisão do grupo<select value={collective.decision} onChange={e=>setCollective({...collective,decision:e.target.value as Collective['decision']})}>{['Avançar','Reserva','Não avançar'].map(s=><option key={s}>{s}</option>)}</select></label><label>Justificativa da decisão *<Textarea value={collective.rationale} onChange={e=>setCollective({...collective,rationale:e.target.value})}/></label>{critical(collective.scores)&&<label>Como o grupo avaliou os alertas de Mentalidade ou Ação? *<Textarea value={collective.criticalJustification} onChange={e=>setCollective({...collective,criticalJustification:e.target.value})}/></label>}<Button type="button" onClick={storeCollective}>Incluir discussão na ficha</Button> <Button type="button" variant="ghost" onClick={()=>setCollective(null)}>Cancelar discussão</Button></div>}</TabsContent>
 <TabsContent value="practice"><p className="preline">{template?.simulation||defaultTemplate().simulation}</p>{(['first','feedback','second','learning'] as const).map((key,i)=><label key={key}>{['Primeira abordagem — evidências','Feedback corretivo oferecido','Repetição — o que mudou','Aprendizado e conclusão'][i]}<Textarea value={c.simulation?.[key]||''} onChange={e=>onChange({...c,simulation:{first:'',feedback:'',second:'',learning:'',...c.simulation,[key]:e.target.value}})}/></label>)}</TabsContent></Tabs></section>;
}

export function TemplatesPanel({state,onSave,busy}:{state:State;onSave:(state:State)=>Promise<boolean>;busy:boolean}){
 const [draft,setDraft]=useState<Template|null>(null),[error,setError]=useState(''),[calendar,setCalendar]=useState(state.holidays.join('\n'));
 return <><div className="sectionbar"><h2>Roteiros por função</h2><Button type="button" onClick={()=>{setError('');setDraft({id:crypto.randomUUID(),name:'',requirements:'',questions:'',simulation:'',tasks:[]});}}>Novo roteiro</Button></div><p>Defina requisitos, entrevistas e tarefas D1, D2, D3. As alterações se aplicam às próximas entradas em etapas; tarefas já criadas são preservadas.</p><div className="job-grid">{state.templates.map(t=><button className="job-card" key={t.id} onClick={()=>{setError('');setDraft(structuredClone(t));}}><h3>{t.name}</h3><p>{t.tasks.length} atividades · MHMA</p><span>Editar roteiro →</span></button>)}</div><details className="calendar"><summary>Calendário de dias úteis</summary><p>Contagem de segunda a sexta, no horário de Brasília. D1 é o dia da entrada, se útil; caso contrário, o próximo dia útil. Cadastre os feriados e recessos aplicáveis abaixo.</p><label>Datas não úteis — uma por linha, AAAA-MM-DD<Textarea rows={5} value={calendar} onChange={e=>setCalendar(e.target.value)}/></label><Button disabled={busy} onClick={async()=>{await onSave({...state,holidays:calendar.split('\n').map(s=>s.trim()).filter(Boolean)});}}>Salvar calendário</Button></details>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="dialog-scroll template-dialog"><DialogHeader><DialogTitle>Roteiro da função</DialogTitle><DialogDescription>Os dias sugeridos são editáveis. D1 começa na entrada em cada etapa.</DialogDescription></DialogHeader>{draft&&<form onSubmit={async e=>{e.preventDefault();setError('');if(!draft.name.trim()||draft.tasks.some(t=>!t.title.trim())){setError('Preencha o nome e os títulos das tarefas.');return;}if(await onSave({...state,templates:state.templates.some(t=>t.id===draft.id)?state.templates.map(t=>t.id===draft.id?draft:t):[...state.templates,draft]}))setDraft(null);else setError('Não foi possível salvar. Verifique os campos e a mensagem no quadro.');}}><fieldset disabled={busy}>{error&&<p className="error">{error}</p>}<label>Nome do roteiro *<Input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{(['requirements','questions','simulation'] as const).map((key,i)=><label key={key}>{['Perfil e requisitos','Perguntas e evidências esperadas','Teste prático'][i]}<Textarea rows={5} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{draft.tasks.map((t,index)=><div className="stage-task" key={t.id}><div className="form-grid"><label>Etapa<select value={t.stage} onChange={e=>setDraft({...draft,tasks:draft.tasks.map(x=>x.id===t.id?{...x,stage:e.target.value}:x)})}>{state.stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Dia útil (D1, D2…)<Input type="number" min={1} max={90} required value={t.day} onChange={e=>setDraft({...draft,tasks:draft.tasks.map(x=>x.id===t.id?{...x,day:Number(e.target.value)}:x)})}/></label></div><label>Atividade *<Input required value={t.title} onChange={e=>setDraft({...draft,tasks:draft.tasks.map(x=>x.id===t.id?{...x,title:e.target.value}:x)})}/></label><label className="task-check"><input type="checkbox" checked={t.required} onChange={e=>setDraft({...draft,tasks:draft.tasks.map(x=>x.id===t.id?{...x,required:e.target.checked}:x)})}/> Obrigatória</label><Button type="button" variant="ghost" onClick={()=>setDraft({...draft,tasks:draft.tasks.filter(x=>x.id!==t.id)})}>Remover atividade {index+1}</Button></div>)}<Button type="button" variant="outline" onClick={()=>setDraft({...draft,tasks:[...draft.tasks,{id:crypto.randomUUID(),title:'',stage:state.stages[0],day:1,required:false}]})}>Adicionar atividade</Button><div className="form-bottom"><Button type="submit">Salvar roteiro</Button></div></fieldset></form>}</DialogContent></Dialog></>;
}

