'use client';
import {useEffect,useState,useRef, type FormEvent} from 'react';
import {moveCandidate,makeMovement,pendingRequired,type Movement} from '@/lib/transition';
import {exitReasons,templateTasks,localDate,score,critical} from '@/lib/process';
import {HomeActivities} from './home-activities';
import type {Activity} from '@/lib/activities';
import {CandidateProcess,TemplatesPanel} from './process-panels';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Search,Plus,ArrowUpRight,BriefcaseBusiness,Users,SlidersHorizontal,Clock,Check,RefreshCw} from 'lucide-react';
import {type Candidate,type Job,type State,candidateSchema,stateSchema} from '@/lib/ats';
const stamp=(v:string)=>new Date(v).toLocaleString('pt-BR');
const day=(v:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'';
const closed=(s:string)=>s==='Contratado'||s==='Não contratado';
export default function Workspace({userName,userEmail,userId}:{userName:string;userEmail:string;userId:string}){
 const [assessmentEditing,setAssessmentEditing]=useState(false);
 const [dragId,setDragId]=useState<string|null>(null),[overStage,setOverStage]=useState<string|null>(null);
 const [movement,setMovement]=useState<Movement|null>(null);
 const suppressClick=useRef(false);
 const boardRef=useRef<HTMLDivElement>(null);
 function beginMove(candidate:Candidate,stage:string){if(busy||movement||candidate.stage===stage)return;setError('');setMovement(makeMovement(candidate,stage,data!));setDragId(null);setOverStage(null);}
 async function confirmMove(e:FormEvent){e.preventDefault();if(!movement||!data)return;try{const current=data.candidates.find(c=>c.id===movement.candidate.id);if(!current)throw Error('Candidato não encontrado.');const updated=moveCandidate(movement,data,userName);if(await save({...data,candidates:data.candidates.map(c=>c.id===updated.id?updated:c)})){setNotice(`${updated.name} movido para ${updated.stage}`);setMovement(null);}}catch(e){setError((e as Error).message);}}
 function addTask(){setMovement(m=>m?{...m,tasks:[...m.tasks,{id:crypto.randomUUID(),title:'',owner:m.candidate.owner,due:'',stage:m.stage,done:false}]}:m);}
 function updateTask(id:string,key:'title'|'owner'|'due',value:string){setMovement(m=>m?{...m,tasks:m.tasks.map(t=>t.id===id?{...t,[key]:value}:t)}:m);}
 const [data,setData]=useState<State|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[jobFilter,setJobFilter]=useState(''),[draft,setDraft]=useState<Candidate|null>(null),[job,setJob]=useState<Job|null>(null),[settings,setSettings]=useState(false),[stageText,setStageText]=useState('');
 async function load(){setError('');try{const r=await fetch('/api/state');const b=await r.json() as {state:State;revision:number;error:string;key:string;name:string};if(!r.ok)throw Error(b.error);setData(b.state);setRevision(b.revision);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!data)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'list_recruitment_candidates',description:'Lista os candidatos cadastrados e suas etapas atuais.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Nenhum parâmetro é aceito.');return data.candidates.map(c=>({id:c.id,name:c.name,stage:c.stage,job:data.jobs.find(j=>j.id===c.jobId)?.title||null}));}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[data]);
 async function save(next:State){if(busy)return false;setBusy(true);setError('');try{const valid=stateSchema.safeParse(next);if(!valid.success)throw Error(valid.error.issues[0].message);const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:next,revision})});const b=await r.json() as {state:State;revision:number;error:string;key:string;name:string};if(!r.ok)throw Error(b.error);setData(next);setRevision(b.revision);setNotice('Alterações salvas');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function completeActivity(activity:Activity){
  if(!data||busy||!activity.taskId)return;
  const candidate=data.candidates.find(c=>c.id===activity.candidateId);
  const task=candidate?.tasks?.find(t=>t.id===activity.taskId);
  if(!candidate||!task||task.done)return;
  const at=new Date().toISOString();
  await save({...data,candidates:data.candidates.map(c=>c.id===candidate.id?{...c,updated:at,tasks:c.tasks?.map(t=>t.id===task.id?{...t,done:true,completedAt:at}:t),history:[{at,text:`Tarefa concluída: ${task.title} · ${userName}`},...c.history]}:c)});
 }
 function createCandidate(){const at=new Date().toISOString();setError('');setDraft({id:crypto.randomUUID(),name:'',phone:'',email:'',linkedin:'',source:'',channel:'',jobId:'',stage:data!.stages[0],owner:'',nextAction:'',due:'',notes:'',evaluation:'',reason:'',created:at,updated:at,resume:null,history:[]});}
 async function saveCandidate(e:FormEvent){e.preventDefault();if(!draft||!data)return;if(assessmentEditing){setError('Inclua ou cancele a avaliação em edição antes de salvar a ficha.');return;}if(!candidateSchema.safeParse(draft).success){setError('Confira nome, e-mail e endereço do LinkedIn (https://).');return;}const old=data.candidates.find(c=>c.id===draft.id);if(old&&old.stage!==draft.stage){beginMove({...draft,stage:old.stage},draft.stage);setDraft(null);return;}const at=new Date().toISOString();const entry=!old?'Candidato cadastrado':old.stage!==draft.stage?`${old.stage} → ${draft.stage}${draft.reason?' • '+draft.reason:''}`:'Cadastro e acompanhamento atualizados';const templateId=draft.templateId||data.jobs.find(j=>j.id===draft.jobId)?.templateId||'';const apply=!old||(!old.templateId&&templateId);const added=apply?templateTasks(data.templates.find(t=>t.id===templateId),draft.stage,draft.owner,data.holidays):[];const updated={...draft,templateId,stageEnteredAt:draft.stageEnteredAt||at,tasks:[...(draft.tasks||[]),...added],updated:at,history:[{at,text:entry},...draft.history]};if(await save({...data,candidates:old?data.candidates.map(c=>c.id===updated.id?updated:c):[...data.candidates,updated]}))setDraft(null);}
 async function upload(file?:File){if(!file||!draft)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const r=await fetch('/api/resume',{method:'POST',body:form});const b=await r.json() as {state:State;revision:number;error:string;key:string;name:string};if(!r.ok)throw Error(b.error);setDraft(d=>d?{...d,resume:b}:d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const candidates=data?.candidates.filter(c=>(!jobFilter||c.jobId===jobFilter)&&(c.name+' '+c.phone+' '+c.source).toLocaleLowerCase().includes(query.toLocaleLowerCase()))||[];
 const today=localDate();
 const overdue=data?.candidates.filter(c=>!closed(c.stage)).reduce((sum,c)=>sum+(c.tasks||[]).filter(t=>!t.done&&t.due&&t.due<today).length,0)||0;
 function field(label:string,key:keyof Candidate,type='text'){return <label>{label}<Input type={type} value={String(draft?.[key]||'')} onChange={e=>setDraft(d=>d?{...d,[key]:e.target.value}:d)} /></label>;}
 const errorBox=error?<div className="error" role="alert">{error}</div>:null;
 return <div className="workspace"><header className="topbar"><a href="/" className="brand">veross<span>PEOPLE</span></a><div className="workspace-name">Recrutamento <span className="tag">Versão 1.2</span></div><span className="account" title={userName}>{userName.split('@')[0]} <span className="avatar">{userName.slice(0,1).toUpperCase()}</span></span><form action="/api/auth/logout" method="post"><Button variant="outline" type="submit">Sair</Button></form></header><main>
 <div className="heading"><div><p className="eyebrow">GESTÃO DE TALENTOS</p><h1>Pessoas. Próximos passos.</h1><p className="subtitle">Acompanhe cada candidatura, do primeiro contato à contratação.</p></div><Button onClick={createCandidate} disabled={!data||busy}><Plus size={18}/> Novo candidato</Button></div>
 {errorBox}<div role="status" className="save-status">{busy?'Salvando…':notice}</div>
 {!data?<div className="empty"><p>{error?'Os cadastros não foram carregados.':'Carregando seus cadastros…'}</p>{error&&<Button onClick={load}>Tentar novamente</Button>}</div>:<>
 <section className="metrics" aria-label="Visão geral"><div><span>Candidatos em processo</span><strong>{data.candidates.filter(c=>!closed(c.stage)).length.toString().padStart(2,'0')}</strong><Users/></div><div><span>Vagas abertas</span><strong>{data.jobs.filter(j=>j.status==='Aberta').length.toString().padStart(2,'0')}</strong><BriefcaseBusiness/></div><div><span>Ações atrasadas</span><strong>{overdue.toString().padStart(2,'0')}</strong><Clock/></div><div><span>Contratações</span><strong>{data.candidates.filter(c=>c.stage==='Contratado').length.toString().padStart(2,'0')}</strong><Check/></div></section>
 <Tabs defaultValue="home"><div className="sectionbar"><TabsList><TabsTrigger value="home">Início</TabsTrigger><TabsTrigger value="pipeline">Processo seletivo</TabsTrigger><TabsTrigger value="jobs">Vagas</TabsTrigger><TabsTrigger value="templates">Roteiros</TabsTrigger></TabsList><div className="actions"><Button variant="ghost" size="sm" onClick={load} disabled={busy}><RefreshCw size={15}/> Atualizar</Button><Button variant="outline" size="sm" onClick={()=>{setStageText(data.stages.join('\n'));setSettings(true);setError('');}}><SlidersHorizontal size={15}/> Editar etapas</Button></div></div>
 <TabsContent value="home"><HomeActivities state={data} identity={{name:userName,email:userEmail,id:userId}} busy={busy} onOpen={c=>{setDraft(structuredClone(c));setError('' );}} onComplete={completeActivity}/></TabsContent><TabsContent value="pipeline"><div className="filters"><label className="search"><Search size={18}/><Input aria-label="Buscar candidatos" placeholder="Buscar por nome, telefone ou origem" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar por vaga" value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><option value="">Todas as vagas</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select><span>{candidates.length} candidatura{candidates.length===1?'':'s'}</span></div>
 <div ref={boardRef} className="board" aria-label="Etapas do recrutamento">{data.stages.map((stage,i)=><section data-stage={stage} className={'column '+(closed(stage)?'terminal':'')+(overStage===stage?' drop-target':'')} key={stage}
 onDragOver={e=>{if(!dragId||busy)return;e.preventDefault();e.dataTransfer.dropEffect='move';setOverStage(stage);const board=boardRef.current;if(board){const rect=board.getBoundingClientRect();if(e.clientX>rect.right-65)board.scrollLeft+=35;else if(e.clientX<rect.left+65)board.scrollLeft-=35;}}}
 onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOverStage(null);}}
 onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-veross-candidate')||dragId;setDragId(null);setOverStage(null);const c=data.candidates.find(c=>c.id===id);if(c)beginMove(c,stage);}}><div className="column-title"><span className="stage-number">{String(i+1).padStart(2,'0')}</span><h2>{stage}</h2><span className="count">{candidates.filter(c=>c.stage===stage).length}</span></div><div className="column-body">{candidates.filter(c=>c.stage===stage).map(c=><button className={'candidate'+(dragId===c.id?' dragging':'')} key={c.id} draggable={!busy&&!movement} disabled={busy} aria-label={c.name+'. Arraste para outra etapa ou use Alt e as setas para mover.'}
 onDragStart={e=>{suppressClick.current=true;setDragId(c.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-veross-candidate',c.id);e.dataTransfer.setData('text/plain',c.id);}}
 onDragEnd={()=>{setDragId(null);setOverStage(null);setTimeout(()=>{suppressClick.current=false;},0);}}
 onKeyDown={e=>{if(e.altKey&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();const target=data.stages[data.stages.indexOf(c.stage)+(e.key==='ArrowRight'?1:-1)];if(target)beginMove(c,target);}}}
 onClick={()=>{if(suppressClick.current)return;setDraft(structuredClone(c));setError('');}}><div className="card-top"><span className="candidate-avatar">{c.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span className="drag-grip" aria-hidden="true">⠿</span></div><h3>{c.name}</h3><p>{data.jobs.find(j=>j.id===c.jobId)?.title||'Vaga a definir'}</p><div className="tags">{c.source&&<span>{c.source}</span>}{c.channel&&<span>{c.channel}</span>}{c.closure&&<span>{c.closure.reason}</span>}{c.collective&&<span>MHMA {score(c.collective.scores)}/100</span>}</div>{c.closure&&<p>Encerrado em: {c.closure.fromStage}</p>}{!!pendingRequired(c).length&&<p>{pendingRequired(c).length} tarefa(s) obrigatória(s) pendente(s)</p>}<div className="card-footer">{c.nextAction||'Definir próxima ação'}{c.due&&<time className={c.due<today&&!closed(c.stage)?'late':''}>{day(c.due)}</time>}</div></button>)}{!candidates.some(c=>c.stage===stage)&&<p className="column-empty">Nenhum candidato</p>}</div></section>)}</div><p className="footnote">Arraste um card para outra etapa e confirme as tarefas no popup. Pelo teclado: selecione o card e use Alt + ← ou →.</p></TabsContent>
 <TabsContent value="jobs"><div className="sectionbar"><h2>Vagas da Veross</h2><Button variant="outline" onClick={()=>setJob({id:crypto.randomUUID(),title:'',area:'',manager:'',description:'',requirements:'',salary:'',status:'Aberta'})}><Plus size={16}/> Nova vaga</Button></div>{!data.jobs.length?<div className="empty"><BriefcaseBusiness size={32}/><h3>Qual será a primeira vaga?</h3><p>Cadastre o cargo para vincular as candidaturas.</p></div>:<div className="job-grid">{data.jobs.map(j=><button className="job-card" key={j.id} onClick={()=>setJob({...j})}><span className="tag">{j.status}</span><h3>{j.title}</h3><p>{j.area||'Área não informada'}</p><p>{data.candidates.filter(c=>c.jobId===j.id).length} candidatos · {j.manager||'Gestor a definir'}</p></button>)}</div>}</TabsContent><TabsContent value="templates"><TemplatesPanel state={data} onSave={save} busy={busy}/></TabsContent></Tabs>
 </>}
 </main><footer>VEROSS <span>Recrutamento · Acesso privado</span></footer>
 <Sheet open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><SheetContent className="detail"><SheetHeader><SheetTitle>{data?.candidates.some(c=>c.id===draft?.id)?'Ficha do candidato':'Novo candidato'}</SheetTitle><SheetDescription>Contato, avaliação e acompanhamento do processo.</SheetDescription></SheetHeader>{draft&&data&&<form className="detail-form" onSubmit={saveCandidate}>{errorBox}<fieldset disabled={busy}><h2>Dados do candidato</h2>{field('Nome completo *','name')}<div className="form-grid">{field('Telefone','phone','tel')}{field('E-mail','email','email')}{field('Origem','source')}{field('Canal','channel')}</div>{field('LinkedIn (https://)','linkedin','url')}<label>Vaga<select value={draft.jobId} onChange={e=>setDraft({...draft,jobId:e.target.value})}><option value="">Vaga a definir</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><h2>Processo e próxima ação</h2><div className="form-grid"><label>Etapa<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{data.stages.map(s=><option key={s}>{s}</option>)}</select></label>{field('Responsável','owner')}</div>{field('Próxima ação','nextAction')}{field('Prazo','due','date')}{draft.closure&&<div className="closure-info"><strong>Não contratado · {draft.closure.reason}</strong><p>Etapa de encerramento: {draft.closure.fromStage}</p><p>{stamp(draft.closure.at)} · {draft.closure.by}</p><p>{draft.closure.notes}</p></div>}<CandidateProcess key={draft.id} candidate={draft} state={data} onChange={setDraft} userName={userName} onEditing={setAssessmentEditing}/><h2>Avaliação e anotações</h2><label>Avaliação<Textarea rows={4} placeholder="Competências avaliadas, evidências e pontos a aprofundar" value={draft.evaluation} onChange={e=>setDraft({...draft,evaluation:e.target.value})}/></label><label>Notas internas<Textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><label>Currículo em PDF · até 10 MB<Input type="file" accept="application/pdf,.pdf" onChange={e=>upload(e.target.files?.[0])}/></label>{draft.resume&&<a className="file-link" href={'/api/resume?key='+encodeURIComponent(draft.resume.key)}>{draft.resume.name} ↓</a>}<h2>Histórico</h2><ol className="history">{draft.history.map((h,i)=><li key={i}><span>{h.text}</span><time>{stamp(h.at)}</time></li>)}</ol></fieldset><div className="form-bottom"><Button type="button" variant="outline" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar candidato'}</Button></div></form>}</SheetContent></Sheet>
 <Dialog open={!!movement} onOpenChange={open=>{if(!open&&!busy){setMovement(null);setError('');}}}><DialogContent className="dialog-scroll"><DialogHeader><DialogTitle>Mover para {movement?.stage}</DialogTitle><DialogDescription>{movement?.candidate.name} · {movement?.candidate.stage} → {movement?.stage}. Inclua as tarefas desta etapa antes de confirmar.</DialogDescription></DialogHeader>{movement&&<form onSubmit={confirmMove}>{errorBox}<fieldset disabled={busy}>{movement.stage==='Não contratado'&&<><label>Motivo do encerramento *<select required value={movement.reason} onChange={e=>setMovement({...movement,reason:e.target.value})}><option value="">Selecione o motivo</option>{exitReasons.map(reason=><option key={reason}>{reason}</option>)}</select></label><label>Observação{movement.reason==='Outro motivo'?' *':''}<Textarea required={movement.reason==='Outro motivo'} value={movement.notes} onChange={e=>setMovement({...movement,notes:e.target.value})}/></label><p className="footnote">Etapa de encerramento: {movement.candidate.stage}. Data e responsável serão registrados automaticamente.</p></>}{data&&movement.stage!=='Não contratado'&&data.stages.indexOf(movement.stage)>data.stages.indexOf(movement.candidate.stage)&&pendingRequired(movement.candidate).length>0&&<div className="warning"><strong>Há tarefas obrigatórias pendentes</strong><ul>{pendingRequired(movement.candidate).map(t=><li key={t.id}>{t.title}</li>)}</ul><label>Justificativa para avançar *<Textarea required value={movement.justification} onChange={e=>setMovement({...movement,justification:e.target.value})}/></label></div>}{!movement.tasks.length&&<p className="footnote">Você pode adicionar tarefas ou confirmar apenas a movimentação. As tarefas anteriores serão mantidas.</p>}{movement.tasks.map((task,index)=><div className="stage-task" key={task.id}><label>Tarefa {index+1}{task.required?' · obrigatória':''} *<Input required autoFocus={index===0} value={task.title} onChange={e=>updateTask(task.id,'title',e.target.value)} placeholder="Ex.: agendar entrevista com o gestor"/></label><div className="form-grid"><label>Responsável<Input value={task.owner} onChange={e=>updateTask(task.id,'owner',e.target.value)}/></label><label>Prazo<Input type="date" value={task.due} onChange={e=>updateTask(task.id,'due',e.target.value)}/></label></div><Button variant="ghost" type="button" onClick={()=>setMovement({...movement,tasks:movement.tasks.filter(t=>t.id!==task.id)})}>Remover tarefa {index+1}</Button></div>)}<Button type="button" variant="outline" onClick={addTask}><Plus size={16}/> Adicionar tarefa</Button></fieldset><div className="form-bottom"><Button type="button" variant="outline" disabled={busy} onClick={()=>{setMovement(null);setError('');}}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Salvando…':'Confirmar movimentação'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!job} onOpenChange={open=>{if(!open&&!busy)setJob(null);}}><DialogContent className="dialog-scroll"><DialogHeader><DialogTitle>{data?.jobs.some(j=>j.id===job?.id)?'Editar vaga':'Nova vaga'}</DialogTitle><DialogDescription>Defina o perfil que a Veross procura.</DialogDescription></DialogHeader>{job&&data&&<form onSubmit={async e=>{e.preventDefault();if(await save({...data,jobs:data.jobs.some(j=>j.id===job.id)?data.jobs.map(j=>j.id===job.id?job:j):[...data.jobs,job]}))setJob(null);}}>{errorBox}<fieldset disabled={busy}>{(['title','area','manager','salary'] as const).map((key,i)=><label key={key}>{['Cargo *','Área','Gestor responsável','Faixa salarial'][i]}<Input required={key==='title'} value={job[key]} onChange={e=>setJob({...job,[key]:e.target.value})}/></label>)}<label>Descrição<Textarea value={job.description} onChange={e=>setJob({...job,description:e.target.value})}/></label><label>Requisitos<Textarea value={job.requirements} onChange={e=>setJob({...job,requirements:e.target.value})}/></label><label>Roteiro da função<select value={job.templateId||''} onChange={e=>setJob({...job,templateId:e.target.value})}><option value="">Sem roteiro</option>{data.templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Status<select value={job.status} onChange={e=>setJob({...job,status:e.target.value as Job['status']})}><option>Aberta</option><option>Pausada</option><option>Encerrada</option></select></label></fieldset><Button type="submit" disabled={busy}>Salvar vaga</Button></form>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={open=>{if(!busy)setSettings(open);}}><DialogContent><DialogHeader><DialogTitle>Etapas do processo</DialogTitle><DialogDescription>Uma etapa por linha, na ordem desejada. Mantenha “Contratado”, “Não contratado” e as etapas que têm candidatos.</DialogDescription></DialogHeader>{errorBox}<Textarea aria-label="Etapas, uma por linha" rows={9} value={stageText} onChange={e=>setStageText(e.target.value)}/><Button disabled={busy} onClick={async()=>{if(data&&await save({...data,stages:stageText.split('\n').map(s=>s.trim()).filter(Boolean)}))setSettings(false);}}>Salvar etapas</Button></DialogContent></Dialog>
 </div>;
}



