import { z } from 'zod';
import {pipeline,taskSchema,assessmentSchema,collectiveSchema,templateSchema,exitReasons,critical,score,pillars} from './process';
export const stages = pipeline;
const str=z.string().max(10000);
export const candidateSchema=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(200),phone:str,email:z.union([z.literal(''),z.string().email()]),linkedin:z.union([z.literal(''),z.string().url().refine(v=>new URL(v).protocol==='https:')]),source:str,channel:str,jobId:str,stage:z.string().min(1),owner:str,nextAction:str,due:str,notes:str,evaluation:str,reason:str,created:str,updated:str,resume:z.object({key:str,name:str}).nullable(),tasks:z.array(taskSchema).max(1000).optional(),templateId:str.optional(),stageEnteredAt:str.optional(),assessments:z.array(assessmentSchema).max(100).optional(),collective:collectiveSchema.nullable().optional(),collectiveHistory:z.array(collectiveSchema).max(100).optional(),simulation:z.object({first:str,feedback:str,second:str,learning:str}).optional(),closure:z.object({reason:z.enum(exitReasons),fromStage:str,at:str,by:z.string().trim().min(1),notes:str}).nullable().optional(),transitionJustification:str.optional(),history:z.array(z.object({at:str,text:str})).max(1000)});
export const jobSchema=z.object({id:z.string().min(1),title:z.string().trim().min(1).max(200),area:str,manager:str,description:str,requirements:str,salary:str,status:z.enum(['Aberta','Pausada','Encerrada']),templateId:str.optional()});
export const stateSchema=z.object({schemaVersion:z.literal(2),templates:z.array(templateSchema).max(100),holidays:z.array(z.string().regex(/^\d{4}-\d{2}-\d{2}$/)).max(1000),stages:z.array(z.string().trim().min(1).max(60)).min(3).max(20),candidates:z.array(candidateSchema).max(3000),jobs:z.array(jobSchema).max(1000)}).superRefine((v,c)=>{if(new Set(v.stages).size!==v.stages.length||!v.stages.includes('Contratado')||!v.stages.includes('Não contratado')||v.candidates.some(x=>!v.stages.includes(x.stage)||x.jobId&&!v.jobs.some(j=>j.id===x.jobId))||new Set(v.candidates.map(x=>x.id)).size!==v.candidates.length||new Set(v.jobs.map(x=>x.id)).size!==v.jobs.length)c.addIssue({code:'custom',message:'Verifique etapas, vagas e cadastros.'});if(v.templates.some(t=>t.tasks.some(x=>!v.stages.includes(x.stage)))||new Set(v.templates.map(t=>t.id)).size!==v.templates.length)c.addIssue({code:'custom',message:'Revise as etapas dos roteiros.'});
if(v.jobs.some(j=>j.templateId&&!v.templates.some(t=>t.id===j.templateId))||v.candidates.some(x=>x.templateId&&!v.templates.some(t=>t.id===x.templateId)))c.addIssue({code:'custom',message:'Selecione um roteiro existente.'});
for(const holiday of v.holidays){const date=new Date(holiday+'T12:00:00Z');if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==holiday)c.addIssue({code:'custom',message:'Informe datas válidas no calendário.'});}
for(const candidate of v.candidates){
if(candidate.closure?.reason==='Outro motivo'&&!candidate.closure.notes.trim())c.addIssue({code:'custom',message:'Descreva o motivo do encerramento.'});
for(const assessment of candidate.assessments||[])if(pillars.some(p=>assessment.scores[p.key]!==null&&!assessment.evidence[p.key].trim()))c.addIssue({code:'custom',message:'Registre evidências para cada nota individual.'});if(candidate.stage==='Não contratado'&&!candidate.closure)c.addIssue({code:'custom',message:'Informe o motivo de encerramento.'});const final=candidate.collective;if(final&&(score(final.scores)===null||Object.values(final.evidence).some(e=>!e.trim())||(critical(final.scores)&&!final.criticalJustification.trim())))c.addIssue({code:'custom',message:'Complete a avaliação coletiva e justifique os alertas.'});}
});
export type Candidate=z.infer<typeof candidateSchema>;
export type Job=z.infer<typeof jobSchema>;
export type State=z.infer<typeof stateSchema>;
export function initialState(){const at=new Date().toISOString();return {stages:[...stages],jobs:[],candidates:[{id:'emanuelle-santos',name:'Emanuelle Santos',phone:'12 98217-4240',email:'',linkedin:'https://www.linkedin.com/in/emanuelle-santos-124162301/',source:'LinkedIn',channel:'InMail',jobId:'',stage:'Novo',owner:'',nextAction:'',due:'',notes:'',evaluation:'',reason:'',created:at,updated:at,resume:null,history:[{at,text:'Cadastro inicial • origem LinkedIn / InMail'}]}]};}

