import {z} from 'zod';
export const pipeline=['Novo','Triagem','Entrevista RH','Apresentação da Veross','Entrevista gestor','Proposta','Contratado','Não contratado'];
export const exitReasons=['Reprovado pela Veross','Desistiu do processo','Sem resposta','Recusou a proposta','Vaga cancelada ou suspensa','Outro motivo'] as const;
const text=z.string().max(10000);
export const taskSchema=z.object({id:z.string().min(1),title:z.string().trim().min(1).max(1000),owner:text,due:text,stage:text,done:z.boolean(),required:z.boolean().optional(),templateTaskId:text.optional(),createdAt:text.optional(),completedAt:text.optional()});
export const scoresSchema=z.object({mindset:z.number().int().min(1).max(5).nullable(),skills:z.number().int().min(1).max(5).nullable(),method:z.number().int().min(1).max(5).nullable(),action:z.number().int().min(1).max(5).nullable()});
export const evidenceSchema=z.object({mindset:text,skills:text,method:text,action:text});
export const assessmentSchema=z.object({id:z.string().min(1),interviewer:z.string().trim().min(1),stage:text,at:text,scores:scoresSchema,evidence:evidenceSchema,positives:text,risks:text,potential:z.enum(['Não avaliado','Baixo','Médio','Alto']),recommendation:z.enum(['Pendente','Avançar','Reserva','Não avançar']),summary:text});
export const collectiveSchema=z.object({participants:z.array(z.string().trim().min(1)).min(1),at:text,scores:scoresSchema,evidence:evidenceSchema,decision:z.enum(['Avançar','Reserva','Não avançar']),rationale:z.string().trim().min(1),criticalJustification:text,recordedBy:z.string().trim().min(1)});
export const templateSchema=z.object({id:z.string().min(1),name:z.string().trim().min(1),requirements:text,questions:text,simulation:text,tasks:z.array(z.object({id:z.string().min(1),stage:z.string().min(1),title:z.string().trim().min(1).max(1000),day:z.number().int().min(1).max(90),required:z.boolean()})).max(200)});
export type Task=z.infer<typeof taskSchema>;
export type Assessment=z.infer<typeof assessmentSchema>;
export type Collective=z.infer<typeof collectiveSchema>;
export type Template=z.infer<typeof templateSchema>;
export type Scores=z.infer<typeof scoresSchema>;
export const pillars=[{key:'mindset',name:'Mentalidade',weight:30},{key:'skills',name:'Habilidades',weight:25},{key:'method',name:'Método',weight:15},{key:'action',name:'Ação',weight:30}] as const;
export const blankScores=():Scores=>({mindset:null,skills:null,method:null,action:null});
export const blankEvidence=()=>({mindset:'',skills:'',method:'',action:''});
export function score(s:Scores){return pillars.some(p=>s[p.key]===null)?null:pillars.reduce((sum,p)=>sum+(s[p.key]!/5)*p.weight,0);}
export function band(s:Scores){const total=score(s);return total===null?'Avaliação incompleta':total>=85?'Avanço prioritário':total>=70?'Avançar':total>=60?'Reserva / segunda avaliação':'Não avançar';}
export function critical(s:Scores){return(s.mindset!==null&&s.mindset<=2)||(s.action!==null&&s.action<=2);}
export function localDate(at=new Date().toISOString()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(at));}
export function businessDate(start:string,day:number,holidays:string[]=[]){const date=new Date(start+'T12:00:00Z');if(Number.isNaN(date.getTime())||!Number.isInteger(day)||day<1||day>90)throw Error('Prazo inválido');let count=0;for(let attempts=0;attempts<1000;attempts++){const iso=date.toISOString().slice(0,10);if(date.getUTCDay()!==0&&date.getUTCDay()!==6&&!holidays.includes(iso)){count++;if(count===day)return iso;}date.setUTCDate(date.getUTCDate()+1);}throw Error('Calendário sem dias úteis disponíveis');}
export function templateTasks(template:Template|undefined,stage:string,owner:string,holidays:string[],at=new Date().toISOString()):Task[]{return(template?.tasks||[]).filter(t=>t.stage===stage).map(t=>({id:crypto.randomUUID(),title:t.title,owner,due:businessDate(localDate(at),t.day,holidays),stage,done:false,required:t.required,templateTaskId:t.id,createdAt:at}));}
export function defaultTemplate():Template {
 const entries:[string,number,string,boolean][]=[['Novo',1,'Conferir cadastro, vincular vaga e fazer o primeiro contato',true],['Novo',2,'Fazer follow-up se não houver resposta',false],['Triagem',1,'Realizar call de até 15 minutos: interesse, requisitos, disponibilidade e pretensão',true],['Triagem',1,'Solicitar convite no LinkedIn e e-mail de apresentação ao CEO',true],['Triagem',2,'Conferir envio do convite no LinkedIn pelo candidato',true],['Triagem',2,'Conferir e avaliar o e-mail de apresentação ao CEO',true],['Entrevista RH',1,'Agendar entrevista por videochamada',true],['Entrevista RH',2,'Entrevistar e registrar MHMA com evidências concretas',true],['Apresentação da Veross',1,'Agendar videochamada com os candidatos e apresentar a Veross',true],['Apresentação da Veross',2,'Registrar comunicação, escuta, preparação e qualidade das perguntas',true],['Entrevista gestor',1,'Agendar entrevista individual com o gestor',true],['Entrevista gestor',2,'Aplicar simulação de prospecção, dar feedback e repetir a abordagem',true],['Entrevista gestor',2,'Registrar MHMA individual do gestor',true],['Entrevista gestor',3,'Discutir com os envolvidos e registrar avaliação coletiva final',true],['Proposta',1,'Apresentar condições e definir prazo de resposta',true],['Proposta',3,'Acompanhar aceite, dúvidas ou recusa da proposta',true],['Contratado',1,'Confirmar início e encaminhar para admissão e integração',true],['Não contratado',1,'Dar retorno ao candidato e registrar o encerramento',true]];
 return {id:'veross-pre-vendas-mhma',name:'Executivo de Pré-Vendas · MHMA',requirements:'Perfil em início ou transição de carreira comercial. Priorizar potencial de desenvolvimento, disciplina, aprendizado e execução consistente.\nMentalidade (30%): autorresponsabilidade, curiosidade, abertura a feedback e persistência.\nHabilidades (25%): comunicação oral e escrita, escuta, pesquisa, síntese e fluência digital.\nMétodo (15%): organização, CRM, cadência, métricas e melhoria contínua.\nAção (30%): cumprimento de combinados, follow-up, constância e aplicação de feedback.',questions:'Entrevista RH — pedir contexto, ação concreta, resultado e aprendizado:\n1. O que decidiu aprender sozinho nos últimos 12 meses? O que fez e até onde chegou?\n2. Conte uma situação em que recebeu vários nãos ou foi ignorado. O que fez depois?\n3. Qual feedback difícil recebeu? O que mudou concretamente?\n4. Fale sobre um resultado ruim em que teve responsabilidade direta.\n5. Qual rotina ou meta sustentou por vários meses?\nGestor — raciocínio comercial:\n6. Você prospectou dez empresas e nenhuma respondeu. O que faz?',simulation:'Briefing simples de uma empresa-alvo.\n1. Preparação: 5 minutos.\n2. Abordagem simulada: 3 a 5 minutos.\n3. Um feedback corretivo do entrevistador.\n4. Repetição imediata de parte da abordagem.\nObservar preparação, clareza, curiosidade, escuta, adaptação e aplicação do feedback.',tasks:entries.map(([stage,day,title,required],i)=>({id:'mhma-'+i,stage,day,title,required}))};
}
